### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by alexzaitsev** [VincentGarreau/particles.js#101]
Hello, i installed particles.js with npm and created a variable in `app.js` but right after this i have a crash:

```
/media/d/Develop/potter/potter.com.ua/node_modules/particles.js/particles.js:1429
window.requestAnimFrame = (function(){
^
ReferenceError: window is not defined
    at Object.<anonymous> (/media/d/Develop/potter/potter.com.ua/node_modules/particles.js/particles.js:1429:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/media/d/Develop/potter/potter.com.ua/app.js:10:19)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

```

Could you help me?

**Comment by thinkTank15** [comment]
Hi did you solve this issue?, I have encountered the same thing.

**Comment by rybealey** [comment]
Running into the same issue. :(

**Comment by Kupstas** [comment]
It's strange. In angular I have no problem. When I try used it in react I have save error.
