### ISSUE TITLE
Redirecting to new page gradually decreases the fps

### ISSUE THREAD

**Issue by SablyTv** [VincentGarreau/particles.js#438]
So basically when I go to another page, for example from "/help" -> "/messages" the frames drop.
[https://gyazo.com/96eb10a3a75e878354659314ef7bfbcd](GIF_EXAMPLE)

But as soon as I either refresh the page or even resizes the browser window the frames go up again.
[https://gyazo.com/6da0a3223f0d8e7c895cbb5d2157d788](GIF_EXAMPLE)

So the code. I tried different types of code implementations, using the files itself. Using the Ruby On Rails gem. But the only thing that works for me is to upload the files to a server, and then using the script element to src the files down again. Here is the code:

CSS
`#particles-js {
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  z-index: -1;
}`

HTML
`<div id="particles-js"></div>`

JS
[https://gyazo.com/dc92ca9966e169542038584ec14d267c](IMAGE)

If you need more info, just tell me

I just noticed that the problem does not appear on mobile devices

**Comment by matteobruni** [comment]
That's because particlesJS creates a new instance every load and never dispose the old one. I suggest you to have a look [here](https://github.com/matteobruni/tsparticles) since this project is abandoned, this library shouldn't be affected by this issue, you can keep the same config.

**Comment by SablyTv** [comment]
Yooo, thanks for the answer. That solved my issue!

**Comment by imyoric** [comment]
> That's because particlesJS creates a new instance every load and never dispose the old one. I suggest you to have a look [here](https://github.com/matteobruni/tsparticles) since this project is abandoned, this library shouldn't be affected by this issue, you can keep the same config.

ahh, but tsparticles not working, im testing 2.11.0 and 2.12.0 and get error:

```

Uncaught (in promise) TypeError: t.replace is not a function
    at tsparticles.engine.min.js:2:31371
    at dt (tsparticles.engine.min.js:2:11265)
    at get ids (tsparticles.engine.min.js:2:31347)
    at me.load (tsparticles.engine.min.js:2:31465)
    at tsparticles.engine.min.js:2:32661
    at dt (tsparticles.engine.min.js:2:11265)
    at _e.load (tsparticles.engine.min.js:2:32627)
    at we.load (tsparticles.engine.min.js:2:33282)
    at mi.load (tsparticles.engine.min.js:2:48450)
    at pi (tsparticles.engine.min.js:2:46703)
```
