### ISSUE TITLE
particals js error

### ISSUE THREAD

**Issue by Trushik0521** [VincentGarreau/particles.js#517]
particles.js:1293 Uncaught TypeError: Cannot read properties of null (reading 'getElementsByClassName')
    at window.particlesJS (particles.js:1293:32)
    at custome.js:73:1
window.particlesJS @ particles.js:1293
(anonymous) @ custome.js:73

**Comment by farouk-tt** [comment]
same issue, here, sucks that this library is not maintained anymore
